insert into PERSON  values (1, 'red', 'Warrior', 0);
insert into PERSON  values (2, 'green', 'Wizard', 0);
insert into PERSON  values (3, 'whilte', 'Priest', 0);
insert into PERSON  values (4, 'yellow', 'Rogue', 0);
insert into PERSON  values (5, 'blue', 'Fighter', 1);
insert into PERSON  values (6, 'lighblue', 'Paladin', 1);
insert into PERSON  values (7, 'lighgreen', 'Ranger', 1);
insert into PERSON  values (8, 'grey', 'Mage', 2);
insert into PERSON  values (9, 'lightgrey', 'Specialist wizard', 2);
insert into PERSON  values (10, 'red', 'Cleric', 3);
insert into PERSON  values (11, 'green', 'Druid', 3);
insert into PERSON  values (12, 'white', 'Priest of specific mythos', 3);
insert into PERSON  values (13, 'yellow', 'Thief', 4);
insert into PERSON  values (14, 'blue', 'Bard', 4);
insert into PERSON  values (15, 'lighblue', 'Assassin', 13);